# NumPy Exercise

In [1]:

import numpy as np
    

### 1. Array creation and basic operations

In [2]:

# (1) Create a 10x10 random array with values between 0 and 100 (int)
arr = np.random.randint(0, 100, (10, 10))
print(arr)
    

[[ 1  3 19  4 75 23 43  2 33 15]
 [68  5 84 72 85 29 44 61 28 86]
 [28 16 48 93 96 59 97 24 58 73]
 [14 39 36 23 23 60 73 75 54 41]
 [ 3 11 71 80 66  9 69 98 90 18]
 [17 73 98 55 13 25 51 73 89 72]
 [86 42 14 60 39  7 54 21 75  2]
 [ 1 70 67 40 77 36  8 44 69 22]
 [78 31 38 89 21 54 11 14 81  3]
 [54 67 93 82 55 87 82 78 71 38]]


In [3]:

# (2) Calculate the minimum, maximum, and mean of the array
min_value = np.min(arr)
max_value = np.max(arr)
mean_value = np.mean(arr)

print("Min:", min_value, "Max:", max_value, "Mean:", mean_value)
    

Min: 1 Max: 98 Mean: 48.52


In [4]:

# (3) Compute the sum of the array along rows or columns
row_sum = np.sum(arr, axis=0)
col_sum = np.sum(arr, axis=1)

print("Row sum:", row_sum)
print("Column sum:", col_sum)
    

Row sum: [350 357 568 598 550 389 532 490 648 370]
Column sum: [218 562 592 438 515 566 400 434 420 707]


### 2. Array reshaping and merging

In [5]:

# (1) Reshape the array into a 5x20 array
reshaped_array = np.reshape(arr, (5, 20))
print("Reshaped array:", reshaped_array)
    

Reshaped array: [[ 1  3 19  4 75 23 43  2 33 15 68  5 84 72 85 29 44 61 28 86]
 [28 16 48 93 96 59 97 24 58 73 14 39 36 23 23 60 73 75 54 41]
 [ 3 11 71 80 66  9 69 98 90 18 17 73 98 55 13 25 51 73 89 72]
 [86 42 14 60 39  7 54 21 75  2  1 70 67 40 77 36  8 44 69 22]
 [78 31 38 89 21 54 11 14 81  3 54 67 93 82 55 87 82 78 71 38]]


In [6]:

# (2) Create a 1x20 array using np.ones, and concatenate it to the reshaped array along the rows
new_array = np.ones((1, 20))
concatenated_array = np.concatenate((reshaped_array, new_array), axis=0)
print("Concatenated array:", concatenated_array)
    

Concatenated array: [[ 1.  3. 19.  4. 75. 23. 43.  2. 33. 15. 68.  5. 84. 72. 85. 29. 44. 61.
  28. 86.]
 [28. 16. 48. 93. 96. 59. 97. 24. 58. 73. 14. 39. 36. 23. 23. 60. 73. 75.
  54. 41.]
 [ 3. 11. 71. 80. 66.  9. 69. 98. 90. 18. 17. 73. 98. 55. 13. 25. 51. 73.
  89. 72.]
 [86. 42. 14. 60. 39.  7. 54. 21. 75.  2.  1. 70. 67. 40. 77. 36.  8. 44.
  69. 22.]
 [78. 31. 38. 89. 21. 54. 11. 14. 81.  3. 54. 67. 93. 82. 55. 87. 82. 78.
  71. 38.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.]]


### 3. Logical operations and filtering

In [7]:

# (1) Use boolean indexing to find all elements greater than 50, and set them to 50
arr = np.where(arr > 50, 50, arr)
print("Array after setting elements > 50 to 50:", arr)
    

Array after setting elements > 50 to 50: [[ 1  3 19  4 50 23 43  2 33 15]
 [50  5 50 50 50 29 44 50 28 50]
 [28 16 48 50 50 50 50 24 50 50]
 [14 39 36 23 23 50 50 50 50 41]
 [ 3 11 50 50 50  9 50 50 50 18]
 [17 50 50 50 13 25 50 50 50 50]
 [50 42 14 50 39  7 50 21 50  2]
 [ 1 50 50 40 50 36  8 44 50 22]
 [50 31 38 50 21 50 11 14 50  3]
 [50 50 50 50 50 50 50 50 50 38]]


In [8]:

# (2) Find the positions of all even numbers in the array
even_positions = np.argwhere(arr % 2 == 0)
print("Even number positions:", even_positions)
    

Even number positions: [[0 3]
 [0 4]
 [0 7]
 [1 0]
 [1 2]
 [1 3]
 [1 4]
 [1 6]
 [1 7]
 [1 8]
 [1 9]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [2 4]
 [2 5]
 [2 6]
 [2 7]
 [2 8]
 [2 9]
 [3 0]
 [3 2]
 [3 5]
 [3 6]
 [3 7]
 [3 8]
 [4 2]
 [4 3]
 [4 4]
 [4 6]
 [4 7]
 [4 8]
 [4 9]
 [5 1]
 [5 2]
 [5 3]
 [5 6]
 [5 7]
 [5 8]
 [5 9]
 [6 0]
 [6 1]
 [6 2]
 [6 3]
 [6 6]
 [6 8]
 [6 9]
 [7 1]
 [7 2]
 [7 3]
 [7 4]
 [7 5]
 [7 6]
 [7 7]
 [7 8]
 [7 9]
 [8 0]
 [8 2]
 [8 3]
 [8 5]
 [8 7]
 [8 8]
 [9 0]
 [9 1]
 [9 2]
 [9 3]
 [9 4]
 [9 5]
 [9 6]
 [9 7]
 [9 8]
 [9 9]]


### 4. Linear algebra operations

In [9]:

# (1) Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("Identity matrix:", identity_matrix)
    

Identity matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:

# (2) Create a 3x3 random matrix and compute its inverse
random_matrix = np.random.rand(3, 3)
inv_matrix = np.linalg.inv(random_matrix)

print("Random matrix:", random_matrix)
print("Inverse matrix:", inv_matrix)
    

Random matrix: [[0.01351419 0.40216112 0.44977255]
 [0.53285893 0.14279069 0.24491588]
 [0.81877238 0.45929049 0.29781044]]
Inverse matrix: [[-0.95353261  1.18312165  0.46710086]
 [ 0.57023356 -4.96421912  3.22131319]
 [ 1.742126    4.40317437 -2.89435048]]


In [11]:

# (3) Matrix multiplication
matrix_product = np.dot(random_matrix, inv_matrix)
print("Matrix product (should be close to identity matrix):", matrix_product)
    

Matrix product (should be close to identity matrix): [[ 1.00000000e+00 -1.54049102e-16  1.31125118e-17]
 [-8.83410814e-18  1.00000000e+00 -4.49041393e-17]
 [ 1.64538676e-17  3.29221542e-16  1.00000000e+00]]
