## Practice

1. Create a 10*10 ndarray object, and the matrix boundary value is 1, and the rest are 0.


In [6]:
#1
import numpy as np
x = np.zeros((10, 10))
x[0, :] = 1
x[-1, :] = 1
x[:, 0] = 1
x[:, -1] = 1
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

2. Create a 5*5 matrix with each row being 0 to 4

In [10]:
#2
x = np.arange(5)
np.vstack([x, x, x, x, x])

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

3. Create an 8*8 matrix and fill it with a checkerboard pattern, like [[0,1],[1,0]])

In [13]:
#3
x = np.zeros((8, 8))
x[::2, 1::2] = 1.
x[1::2, ::2] = 1.
x

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

4. output all the odd numbers in the array  
   Example:  
   in:    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])  
   out:   array([1, 3, 5, 7, 9])  

In [18]:
#4
arr = np.arange(10)
arr[arr % 2 == 1]


array([1, 3, 5, 7, 9])

5. Normalize a 5x5 random matrix.(Z-Score Normalization零均值归一化)

In [25]:
#5
from numpy.random import default_rng
x = default_rng().random((5, 5))
x = (x - np.mean(x)) / np.std(x)
x

array([[-0.47534048,  0.75945009, -0.04167872, -0.21844627,  0.37054103],
       [ 0.44669665,  0.88037662, -1.76626806, -0.60591332,  0.4688628 ],
       [-1.40775916,  0.18911164,  1.84253934,  0.99616817,  0.60987908],
       [ 0.87256815, -0.14813189,  1.53061517, -1.11161652,  1.71580812],
       [-0.89734924, -0.75697008, -1.30042429, -1.34430757, -0.60841127]])

6. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates.

In [28]:
#6
x = default_rng().random(10)
y = default_rng().random(10)
r = np.sqrt(x**2 + y**2)
t = np.arctan2(y, x)
r, t

(array([1.0458816 , 0.55797964, 0.75845656, 1.06721403, 0.22227568,
        0.95575933, 1.09197024, 0.71635189, 1.12906668, 1.21566037]),
 array([0.6103544 , 1.20334686, 0.789245  , 0.5885365 , 0.28832615,
        1.22588594, 0.77597619, 1.07545846, 0.68667408, 0.75335771]))

7. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [48]:
#7
arr = np.arange(5) + 1
x = np.zeros(len(arr) * 4 - 3, dtype = int)
x[::4] = arr
x


array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

8. What are the result of the following expressions?

0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

np.nan in set([np.nan])

0.3 == 3 * 0.1 

(hint1:nan means not a number 
hint2:0.1(10) == 0.0001100110011001100110011001100110011001100110011...(2))
First guess a result, then print the result, and finally find why

In [54]:
#8
0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

np.nan in set([np.nan])

0.3 == 3 * 0.1 

False

9. What are the result of the following expressions? (Hint: the type of pn.nan is float)

np.array(0) / np.array(0)

np.array(0) // np.array(0)

np.array([np.nan]).astype(int).astype(float)


First guess a result, then print the result, and finally find why 

In [56]:
#9
np.array(0) // np.array(0)

/tmp/ipykernel_3053/2387531771.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0